---
title: "¬"
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'Atul''s Programming Journals. A blog where I explore programming & Design

'
baseurl: ''
url: http://avinayak.github.io
author:
  fullname: Atul Vinayak
  github: avinayak
  twitter: atulvinayak
  unsplash: atulvi
highlightstyle: github-gist
styles:
- agate
- androidstudio
- arta
- asceti
- atelier-cave.dark
- atelier-cave.light
- atelier-dune.dark
- atelier-dune.light
- atelier-estuary.dark
- atelier-estuary.light
- atelier-forest.dark
- atelier-forest.light
- atelier-heath.dark
- atelier-heath.light
- atelier-lakeside.dark
- atelier-lakeside.light
- atelier-plateau.dark
- atelier-plateau.light
- atelier-savanna.dark
- atelier-savanna.light
- atelier-seaside.dark
- atelier-seaside.light
- atelier-sulphurpool.dark
- atelier-sulphurpool.light
- brown_paper
- codepen-embed
- color-brewer
- dark
- darkula
- default
- docco
- far
- foundation
- github
- github-gist
- googlecode
- grayscale
- hopscotch
- hybrid
- idea
- ir_black
- kimbie.dark
- kimbie.light
- magula
- mono-blue
- monokai
- monokai_sublime
- obsidian
- paraiso.dark
- paraiso.light
- pojoaque
- railscast
- rainbow
- school_book
- solarized_dark
- solarized_light
- styles_list.txt
- sunburst
- tomorrow
- tomorrow-night-blue
- tomorrow-night-bright
- tomorrow-night
- tomorrow-night-eightie
- v
- xcode
- zenburn
exclude:
- README.md
- README.html
highlighter: 
markdown: kramdown
